"""Synthetic medium/warning examples for CredHunter-X."""

SERVICE_API_KEY = "CHX_SERVICE_API_KEY_MEDIUM_3A6D9G2J5M8P1S4V7Y0B"

WEBHOOK_SIGNING_SECRET = "CHX_WEBHOOK_SECRET_MEDIUM_8C1F4H7K0N3Q6T9W2Z5D"
